---
- hosts: localhost
  connection: localhost
  vars_files:
    - ../vault/vault_key.yml
    - ../vars/aws_secrets.yml

  tasks:
    - name: Upload SSH key to aws
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        key_material: "{{ ssh_public_key }}"
        state: present