- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    key_name: "TempKeyPair"
    instance_type: t2.micro
    security_group: default
    region: us-east-2
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"     
    network:
      assign_public_ip: true
    image_id: "{{ item.image }}"
    tags:
      environment: "{{ item.name }}"
  loop:
    - { image: "ami-0100e595e1cc1ff7f", name: "node1" }
    - { image: "ami-04f167a56786e4b09", name: "node2" }
    - { image: "ami-04f167a56786e4b09", name: "node3" }
