---
- hosts: all
  become: true
  gather_facts: true

  tasks: 
    - name: Shutdown ubuntu instances nly
      ansible.builtin.command: /sibn/shutdown -t now
      when: 
       ansible_facts['os_family'] == "Debian"