---
- name: Configure Apache on the webservers.
  hosts: webservers
  become: true
  gather_facts: false
  roles:
    - httpd
  tags:
    - apache

- name: Configure NGINX Load Balancer (Optional TLS)
  hosts: loadbalancer
  become: true
  gather_facts: false
  roles:
    - nginx
  tags:
     - nginx