---
- name: Create a a user on your local server
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create a user
      ansible.builtin.user:
        name: james
        create_home: yes

    - name: Remove the user johnd
      ansible.builtin.user:
        name: johnd
        state: absent
        remove: yes
