Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 900

  servers = [
    {
      :hostname => "db01",
      :box => "bento/ubuntu-22.04",
      :ip => "",
      :ssh_port => '2210'
    },
    {
      :hostname => "web01",
      :box => "bento/ubuntu-22.04",
      :ip => "",
      :ssh_port => '2211',
      :http_forward => 8080,
      :https_forward => 8441
    },
    {
      :hostname => "web02",
      :box => "bento/ubuntu-22.04",
      :ip => "",
      :ssh_port => '2212',
      :http_forward => 8081,
      :https_forward => 8442
    },
    {
      :hostname => "loadbalancer",
      :box => "bento/ubuntu-22.04",
      :ip => "",
      :ssh_port => '2213',
      :http_forward => 8048,
      :https_forward => 8443
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]

      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      # Forward HTTP/HTTPS only if specified
      if machine[:http_forward]
        node.vm.network "forwarded_port", guest: 80, host: machine[:http_forward], auto_correct: true
      end
      if machine[:https_forward]
        node.vm.network "forwarded_port", guest: 443, host: machine[:https_forward], auto_correct: true
      end

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--name", machine[:hostname]]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
      end
    end
  end
end
